### ISSUE TITLE
Robot pose mismatch in morse simulator and Rviz

### ISSUE THREAD

**Issue by amdshameer** [strands-project/planning_tutorial#3]
I followed this [planning tutorial exercise](https://github.com/strands-project/planning_tutorial/blob/ori/doc/exercise_1.md). But I changed the initial pose of the robot in [tsc simulation environment](https://github.com/strands-project/strands_morse/blob/indigo-devel/tsc/tsc.py#L12). There seems to be a mismatch of robot pose in morse simulator and Rviz. I think it is due to rosparam [/amcl/initial_pose_x](https://github.com/strands-project/planning_tutorial/blob/ori/launch/tsc_navigation.launch#L2) and [/amcl/initial_pose_y](https://github.com/strands-project/planning_tutorial/blob/ori/launch/tsc_navigation.launch#L3). Setting of /amcl/initial_pose_x and /amcl/initial_pose_y was not helpful.

![blend](https://user-images.githubusercontent.com/3973522/41843294-756c1c82-786d-11e8-9827-2c6f8017345f.png)

![rviz](https://user-images.githubusercontent.com/3973522/41843300-78cbe2fe-786d-11e8-9519-318207deb083.png)

Any comment/input on this would be really helpful @hawesie @bfalacerda

**Comment by hawesie** [comment]
The solution is to use the "2D Pose Estimate" button in rviz and set the pose in rviz to the one in the simulation. Let us know if it works!

**Comment by amdshameer** [comment]
Yes. It worked. Thank you!
