### ISSUE TITLE
Laser scan error

### ISSUE THREAD

**Issue by amdshameer** [strands-project/planning_tutorial#4]
I have created a custom blender model for a map in [http://www.cs.cmu.edu/~coral/cobot/data.html](http://www.cs.cmu.edu/~coral/cobot/data.html) The blender, pgm, svg and yaml files can be found [here](https://github.com/amdshameer/blender_map). I scaled the map by following this [link](https://github.com/strands-project/strands_documentation/blob/master/docs/setup.rst#blender-model). The corridors in the map were 8 pixel wide. In order to make it 1.5m wide, I have **scaled the map to 531.56 along x and y axis**. **Resolution of my map is 0.1875** and it can be found in this [yaml](https://github.com/amdshameer/blender_map/blob/master/map.yaml). After launching the necessary launch files, I was able to bring up the robot in morse simulator and visualize the same in Rviz. I was also able to launch navigation modules. Now the issue is, there is a mismatch of laser scan and so the robot is not able to move to a goal pose using "2D Nav Goal". But it can generate the necessary path in  Rviz. Is there any way to fix this laser scan issue?

Initial pose of the robot in Morse and Rviz
![morse](https://user-images.githubusercontent.com/3973522/42452400-2acaa6d0-838a-11e8-8cc1-0e3d95500a38.png)

![rviz](https://user-images.githubusercontent.com/3973522/42452424-3ba21b32-838a-11e8-8d3e-b82207b2b770.png)

**Lase scan values are off**  - After rotating(a full circle) in the same spot
![laser_scan_values_off](https://user-images.githubusercontent.com/3973522/42452440-496cf660-838a-11e8-9e86-fecdfc0c09b2.png)

Move base can plan a path (path is marked)
![2dnavgoal](https://user-images.githubusercontent.com/3973522/42452519-8862b4c2-838a-11e8-941c-4969f46dbf44.png)

To me, it seems like a transformation error.

@hawesie @bfalacerda 
It would be really helpful if you could comment on this.

**Comment by bfalacerda** [comment]
Hi @amdshameer .

I think your problem is with the scaling of the map you are using, not with the morse simulation. I have less experience with that tbh, but I'd suggest you confirm the math you did for the scaling is right. It seems the map you are using is some factor smaller than the simulation environment.

**Comment by amdshameer** [comment]
Hi @bfalacerda 
Yes. My map resolution was wrong. The correct value is 0.1475 Thank you so much
